/**
 * Call Export Utilities
 * Export calls to PDF, TXT, and CSV formats
 */

interface TranscriptEntry {
  role: 'user' | 'agent';
  text: string;
  timestamp?: string;
}

interface CallData {
  id: string;
  createdAt: string;
  durationSeconds: number;
  personalityName: string;
  transcript: TranscriptEntry[];
  score?: {
    overallScore: number;
    categoryScores: Array<{
      category: string;
      score: number;
      maxScore: number;
    }>;
  };
}

/**
 * Export call transcript as plain text
 */
export function exportAsText(call: CallData): string {
  const lines: string[] = [];

  // Header
  lines.push('='.repeat(60));
  lines.push(`DIALDRILL CALL TRANSCRIPT`);
  lines.push('='.repeat(60));
  lines.push('');
  lines.push(`Call ID: ${call.id}`);
  lines.push(`Date: ${new Date(call.createdAt).toLocaleString()}`);
  lines.push(`Duration: ${Math.floor(call.durationSeconds / 60)}:${(call.durationSeconds % 60).toString().padStart(2, '0')}`);
  lines.push(`Personality: ${call.personalityName}`);

  if (call.score) {
    lines.push(`Overall Score: ${call.score.overallScore.toFixed(1)}/10`);
  }

  lines.push('');
  lines.push('-'.repeat(60));
  lines.push('TRANSCRIPT');
  lines.push('-'.repeat(60));
  lines.push('');

  // Transcript
  call.transcript.forEach((entry, index) => {
    const speaker = entry.role === 'user' ? 'Sales Rep' : 'Prospect';
    lines.push(`[${speaker}]`);
    lines.push(entry.text);
    lines.push('');
  });

  // Score breakdown
  if (call.score) {
    lines.push('-'.repeat(60));
    lines.push('SCORE BREAKDOWN');
    lines.push('-'.repeat(60));
    lines.push('');

    call.score.categoryScores.forEach((cat) => {
      lines.push(`${cat.category}: ${cat.score}/${cat.maxScore}`);
    });
  }

  lines.push('');
  lines.push('='.repeat(60));
  lines.push(`Generated by DialDrill - ${new Date().toLocaleString()}`);
  lines.push('='.repeat(60));

  return lines.join('\n');
}

/**
 * Export call as CSV (for bulk analysis)
 */
export function exportAsCSV(calls: CallData[]): string {
  const lines: string[] = [];

  // Header
  lines.push([
    'Call ID',
    'Date',
    'Duration (seconds)',
    'Personality',
    'Overall Score',
    'Opening Score',
    'Discovery Score',
    'Objection Handling Score',
    'Clarity Score',
    'Closing Score',
    'Transcript Word Count',
    'User Turn Count',
  ].join(','));

  // Rows
  calls.forEach((call) => {
    const scores = call.score?.categoryScores || [];
    const getScore = (category: string) => {
      const cat = scores.find((s) => s.category.toLowerCase() === category.toLowerCase());
      return cat ? cat.score.toString() : '';
    };

    const userTurnCount = call.transcript.filter((t) => t.role === 'user').length;
    const wordCount = call.transcript.reduce((sum, t) => sum + t.text.split(/\s+/).length, 0);

    lines.push([
      call.id,
      new Date(call.createdAt).toISOString(),
      call.durationSeconds.toString(),
      `"${call.personalityName}"`,
      call.score?.overallScore.toFixed(1) || '',
      getScore('opening'),
      getScore('discovery'),
      getScore('objectionHandling'),
      getScore('clarity'),
      getScore('closing'),
      wordCount.toString(),
      userTurnCount.toString(),
    ].join(','));
  });

  return lines.join('\n');
}

/**
 * Generate download filename
 */
export function generateFilename(call: CallData, format: 'txt' | 'csv' | 'pdf'): string {
  const date = new Date(call.createdAt).toISOString().split('T')[0];
  const personality = call.personalityName.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  return `dialdrill_${date}_${personality}_${call.id.slice(0, 8)}.${format}`;
}

/**
 * Trigger browser download
 */
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
